language: scala

after_script:
  - if [[ $TRAVIS_TEST_RESULT == 0 && "$TRAVIS_BRANCH" == "master" ]]; then sbt "^publish"; fi

scala:
  - "2.9.2"

# Sonatype secure
env:
  global:
  - secure: "UJh2caCAZsoRpXChgZDqRwe4td3hqo8KTjzr42X8SMFjRLvnxpoHDyEmGRRdX/pkdU6ktga0k7CDGVFwLYSttRZY4GojF+F1bInv3gmFEvsS/6ZNy01q75mg+QIcuOZeyYH2ziGy4kLkAWYCM8fGqtnYLZQks1isu4zpIqujGwk="
  - secure: "m7n/S66NeaO8fWMqPGjesELkWvjpQxFdFmoSMylerXvnY+xwRx1xYHiWrEOrG8kB/kX6+BCwan1QsJ6qn3HPaetG+iTg/AR9mHMy+CgCKhub+V7oy+EXmtaarsAMvxoRxpx9RGrwoFRlozm+fNnSdoY4kt0QNCJOXXY1F8igaes="
